config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "registrations" }

  root 'pages#home'

  get '/confirm_your_email' => 'pages#confirmation'
  get '/success' => 'pages#confirmation_success'

  resources :users, only: %w[] do
    collection do
      get :registrations
    end

    member do
      get :confirm
    end
  end

  resource :search, only: [] do
    collection do
      get :cities
    end
  end

end

app/models/settings.rb
class Settings < Settingslogic
  source "#{Rails.root}/config/application.yml"
  namespace Rails.env
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  confirmation_token     :string(255)
#  confirmed_at           :datetime
#  confirmation_sent_at   :datetime
#  unconfirmed_email      :string(255)
#  ip_detected_location   :string(255)
#  city                   :string(255)
#  browser                :string(255)
#  referrals              :integer
#  created_at             :datetime
#  updated_at             :datetime
#  referral_token         :string(255)
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  after_create :generate_referral_token

  def generate_referral_token
    self.referral_token = Devise.friendly_token
    self.confirmation_token = Devise.friendly_token
    save!
  end

  def confirmed?
    self.confirmed_at != nil
  end

  def confirm(token)
    unless confirmed? && token == confirmation_token
      self.confirmed_at = DateTime.now
      save
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @user = User.new
  end

  def confirmation
    @ref = params[:ref]
    @sign_ups = User.where(city: params[:city]).where.not(confirmed_at: nil).count
  end

  def confirmation_success
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def create
    @user = User.new user_params
    if @user.save
      UserMailer.send_confirm_email(@user).deliver
      subscribe_to_mailchimp(@user.email)
      count_referrals
      redirect_to URI.encode("/confirm_your_email?city=#{@user.city}&ref=#{@user.id}"), notice: "Success"
    else
      redirect_to '/', notice: "Error: #{@user.errors.full_messages}"
    end
  end

  private

  def count_referrals
    if params[:ref]
      user = User.find(params[:ref])
      user.referrals = user.referrals ? user.referrals + 1 : 1
      user.save
    end
  end

  def subscribe_to_mailchimp(email)
    list_id = "42868ea987"
    gb = Gibbon::API.new
    result = gb.lists.subscribe({
      :id => list_id,
      :email => {:email => email}
    })
  end

  def user_params
    if Rails.env.test? || Rails.env.development?
      @location ||= Geocoder.search("50.78.167.161").first
    else
      @location ||= request.location
    end
    city = @location.city
    params.require(:user).permit(:email, :city).merge(password: Devise.friendly_token.first(8),
                                                      ip_detected_location: city,
                                                      browser: browser.name )
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def cities
    keyword = (params[:q] || "Ha").downcase
    all_cities = Settings.cities.values.flat_map(&:values)
    cities = all_cities.select { |x| x.downcase.match(/#{keyword}/).present? }
    render json: cities.as_json
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate, only: [:registrations]
  def confirm
    @user = User.find(params[:id])
    if @user.confirm (params[:token])
      redirect_to '/success', notice: "Success"
    else
      redirect_to '/success', notice: "Invalid!"
    end
  end

  def registrations
    @users = User.page(params[:page]).per(20)
  end


  def authenticate
    authenticate_or_request_with_http_basic('Administration') do |username, password|
      username == 'admin' && password == 'admin'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LandingPage</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header class="navbar navbar-static-top" id="top" role="banner">
    <div class="container">
      <div class="navbar-header">
        <a href="/" class="navbar-brand">Project Name</a>
      </div>
      <nav class="collapse navbar-collapse bs-navbar-collapse" role="navigation">
        <ul class="nav navbar-nav navbar-right">
          <li><a href="#">Contact</a></li>
          <li><a href="#">Login</a></li>
        </ul>
      </nav>
    </div>
  </header>
  <div class="main-content">
    <%= yield %>
  </div>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= yield :javascripts %>
</body>
</html>

app/views/pages/confirmation.html.erb
<div class="white-background">
  <div class="confirmation-page">
    <div class="row">
      <div class="col-md-6">
        <h1>Get There Faster!</h1>
        <%= render 'share_btn' %>
        <br>
        <p>
          Collaboratively evisculate top-line internal or "organic" sources whereas turnkey growth strategies. Rapidiously monetize proactive value without high-payoff models. Quickly architect bleeding-edge metrics before standards compliant architectures. Seamlessly leverage existing client-focused scenarios for principle-centered methods of.
        </p>
      </div>
      <div class="col-md-6">
        <div class="circle">
          <div class="inner">
            <p class="number"><%= @sign_ups %></p>
            <p class="text">Sign-ups in your area!</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/confirmation_success.html.erb
Thank you for confirming

app/views/pages/home.html.erb
<div class="blue-background">
  <div class="landing-page">
    <h1 class="message">Get your city invited.</h1>

    <div class="row signup-panel">
      <div class="col-xs-4 left-message">
        <p> Sign up for an invite today. Cities with most votes will be invited as we roll out.</p>
      </div>
      <div class="col-xs-8">
        <div class="signup-form clearfix">
          <% reg_url = params[:ref] ? "#{registration_path(@user)}?ref=#{params[:ref]}" : registration_path(@user) %>
          <%= simple_form_for(@user, url: reg_url) do |f| %>
            <%= f.error_notification %>
            <div class="form-inputs form-group clearfix">
              <div class="col-xs-3">
                <%= label_tag(:email, "Email") %>
              </div>
              <div class="col-xs-7">
                <%= f.input :email, label: false , autofocus: true, input_html: { class: 'form-control' } %>
              </div>
            </div>

            <div class="clearfix"></div>
            <div class="form-inputs form-group clearfix">
              <div class="col-xs-3">
                <%= label_tag(:city, "City") %>
              </div>
              <div class="col-xs-7">
                <%= f.input :city, label: false, input_html: { class: 'form-control' } %>
                <%#= f.input :city, :as => :select, :collection => ['Add New', 'kaka'], include_blank: true, label: false %>
              </div>
            </div>

            <div class="clearfix"></div>
            <div class="form-group clearfix">
              <div class="col-xs-3"></div>
              <div class="col-xs-7">
                <%= f.button :submit, "Sign up", class: 'btn btn-submit' %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>

    <div class="row foot-message">
      <p> Text is the best way text write copy your next write text copy </p>
    </div>
  </div>
<%= content_for :javascripts do %>
  <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?v=3.exp&libraries=places"></script>
  <script type="text/javascript">
    $(document).ready(function(){
      initialize();
    });

    function format(state) {
      return state;
    }

    function formatSelect(state){
      return state;
    }
    
    function initialize(){
      var input = document.getElementById('user_city');
      var autocomplete = new google.maps.places.Autocomplete(input);
      google.maps.event.addListener(autocomplete, 'place_changed', function() {
        var place = autocomplete.getPlace();
      });
    }
    /*
    $("input#user_city").select2({
      multiple: true,
      maximumSelectionSize: 1,
      minimumInputLength: 1,
      id: function(bond){ return bond; },
      ajax: {
          url: "/search/cities",
          data: function(term) {
            return {
              q: term
            }
          },
          dataType: 'json',
          results: function (data, page) {
            return {results: data};
          }
      },
      initSelection: function(element, callback) {
        $.ajax("/search/cities", {
            dataType: "json"
        }).done(function(data) { callback(data); });
      },
      formatResult: format,
      formatSelection: format,
      // dropdownCssClass: "bigdrop", // apply css that makes the dropdown taller
      escapeMarkup: function (m) { return m; } // we do not want to escape markup since we are displaying html in results
    });
    */
  </script>
<% end %>
</div>

app/views/users/registrations.html.erb
<div class="container">
  <div class="list-users">
    <h2>All Users</h2>

    <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th>#</th>
          <th>IP detected</th>
          <th>Email</th>
          <th>City</th>
          <th>Time and Date of signup</th>
          <th>Browser</th>
          <th>Referrals</th>
          <th>Confirmed?</th>
        </tr>
      </thead>
      <tbody>
        <% @users.each_with_index do |user, index| %>
          <tr>
            <td><%= index + 1 + ((params[:page] || 1).to_i - 1) * 20 %></td>
            <td><%= user.ip_detected_location %></td>
            <td><%= user.email %></td>
            <td><%= user.city %></td>
            <td><%= user.created_at %></td>
            <td><%= user.browser %></td>
            <td><%= user.referrals || 0 %></td>
            <td><%= user.confirmed? %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= paginate @users %>
  </div>
</div>